# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python deps
      run: pip install pillow requests
    - name: Run a one-line script
      run: python ./.github/workflows/sync_template.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: Commit report
      run: |
          git config --global user.name 'rplacesuperstonk'
          git config --global user.email 'rplacesuperstonk@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "sync image"
          git push
